// Generate a compact Rust range table for Unicode \p{M} (Mn|Mc|Me), for the qwen35
// pre-tokenizer mark-folding fix. Output: mark_ranges.rs.inc (sorted inclusive ranges).
import fs from 'fs';
const isMark = (cp) => /\p{M}/u.test(String.fromCodePoint(cp));
const ranges = [];
let start = -1;
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) { if (start >= 0) { ranges.push([start, cp - 1]); start = -1; } continue; }
  if (isMark(cp)) { if (start < 0) start = cp; }
  else if (start >= 0) { ranges.push([start, cp - 1]); start = -1; }
}
if (start >= 0) ranges.push([start, 0x10ffff]);
const body = ranges.map(([a, b]) => `    (0x${a.toString(16).toUpperCase()}, 0x${b.toString(16).toUpperCase()}),`).join('\n');
fs.writeFileSync(new URL('./mark_ranges.rs.inc', import.meta.url),
  `// Unicode \\p{M} (Mn|Mc|Me) inclusive codepoint ranges, generated by gen_mark_table.mjs\n// (Node ${process.version} Unicode tables). ${ranges.length} ranges.\n&[\n${body}\n]\n`);
console.log(`ranges: ${ranges.length}, first: ${ranges[0]}, last: ${ranges.at(-1)}`);
