/* Curated set of models Camelid supports for local chat (exact rows it knows how
   to download + run). Catalog ids/repos/filenames/sizes match the backend catalog
   the install endpoint expects, so installCatalogModel(item) and the localStorage
   download-progress tracking (keyed by catalog_id) work directly. */
export const SUPPORTED_MODELS = [
  {
    catalog_id: 'llama32_3b_instruct_q8_0',
    name: 'Llama 3.2 3B Instruct',
    repo_id: 'unsloth/Llama-3.2-3B-Instruct-GGUF',
    filename: 'Llama-3.2-3B-Instruct-Q8_0.gguf',
    size_bytes: 3422709216,
    quant: 'Q8_0',
    blurb: 'Good at everyday chat, summarizing, and writing — a solid all-rounder.',
    recommended: true,
  },
  {
    catalog_id: 'llama32_1b_instruct_q8_0',
    name: 'Llama 3.2 1B Instruct',
    repo_id: 'unsloth/Llama-3.2-1B-Instruct-GGUF',
    filename: 'Llama-3.2-1B-Instruct-Q8_0.gguf',
    size_bytes: 1346203104,
    quant: 'Q8_0',
    blurb: 'A small, fast model for quick chat and simple tasks.',
  },
  {
    catalog_id: 'tinyllama_1_1b_chat_q8_0',
    name: 'TinyLlama 1.1B Chat',
    repo_id: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF',
    filename: 'tinyllama-1.1b-chat-v1.0.Q8_0.gguf',
    size_bytes: 1169007424,
    quant: 'Q8_0',
    blurb: 'A tiny chat model for basic conversation and quick experiments.',
  },
  {
    catalog_id: 'llama3_8b_instruct_q8_0',
    name: 'Llama 3 8B Instruct',
    repo_id: 'MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF',
    filename: 'Meta-Llama-3-8B-Instruct.Q8_0.gguf',
    size_bytes: 8540846592,
    quant: 'Q8_0',
    blurb: 'Higher-quality chat, reasoning, and longer-form writing.',
  },
  {
    catalog_id: 'mistral_7b_instruct_v0_3_q8_0',
    name: 'Mistral 7B Instruct v0.3',
    repo_id: 'bartowski/Mistral-7B-Instruct-v0.3-GGUF',
    filename: 'Mistral-7B-Instruct-v0.3-Q8_0.gguf',
    size_bytes: 7702565088,
    quant: 'Q8_0',
    blurb: 'Strong at reasoning, coding, and following detailed instructions.',
  },
  {
    catalog_id: 'qwen3_0_6b_instruct_q8_0',
    name: 'Qwen3 0.6B',
    repo_id: 'Qwen/Qwen3-0.6B-GGUF',
    filename: 'Qwen3-0.6B-Q8_0.gguf',
    size_bytes: 639446688,
    quant: 'Q8_0',
    blurb: 'A compact multilingual model for quick chat and light reasoning.',
  },
  {
    catalog_id: 'qwen3_1_7b_instruct_q8_0',
    name: 'Qwen3 1.7B',
    repo_id: 'Qwen/Qwen3-1.7B-GGUF',
    filename: 'Qwen3-1.7B-Q8_0.gguf',
    size_bytes: 1834426016,
    quant: 'Q8_0',
    blurb: 'Multilingual chat with good reasoning and coding for its size.',
  },
  {
    catalog_id: 'qwen3_4b_instruct_q8_0',
    name: 'Qwen3 4B',
    repo_id: 'Qwen/Qwen3-4B-GGUF',
    filename: 'Qwen3-4B-Q8_0.gguf',
    size_bytes: 4280404704,
    quant: 'Q8_0',
    blurb: 'Strong multilingual reasoning, math, and coding, with optional step-by-step thinking.',
  },
  {
    catalog_id: 'qwen3_8b_instruct_q8_0',
    name: 'Qwen3 8B',
    repo_id: 'Qwen/Qwen3-8B-GGUF',
    filename: 'Qwen3-8B-Q8_0.gguf',
    size_bytes: 8709518112,
    quant: 'Q8_0',
    blurb: 'Top-tier Qwen3 quality — strong reasoning, math, coding, and multilingual chat.',
  },
  {
    catalog_id: 'gemma4_e4b_it_q8_0',
    name: 'Gemma 4 E4B-It',
    repo_id: 'unsloth/gemma-4-E4B-it-GGUF',
    filename: 'gemma-4-E4B-it-Q8_0.gguf',
    size_bytes: 8192951456,
    quant: 'Q8_0',
    blurb: 'Google’s Gemma — capable multilingual chat and reasoning.',
  },
  {
    catalog_id: 'gemma4_e2b_it_q8_0',
    name: 'Gemma 4 E2B-It',
    repo_id: 'unsloth/gemma-4-E2B-it-GGUF',
    filename: 'gemma-4-E2B-it-Q8_0.gguf',
    size_bytes: 5048350848,
    quant: 'Q8_0',
    blurb: 'A compact Gemma model for multilingual chat.',
  },
  {
    catalog_id: 'gemma4_12b_it_q8_0',
    name: 'Gemma 4 12B-It (distributed)',
    repo_id: 'unsloth/gemma-4-12b-it-GGUF',
    filename: 'gemma-4-12b-it-Q8_0.gguf',
    size_bytes: 12669646240,
    quant: 'Q8_0',
    blurb: 'A larger Gemma for higher-quality multilingual chat and reasoning.',
  },
  {
    catalog_id: 'gemma4_26b_a4b_it_q4_0',
    name: 'Gemma 4 26B-A4B-It QAT (distributed, MoE)',
    repo_id: 'google/gemma-4-26B-A4B-it-qat-q4_0-gguf',
    filename: 'gemma-4-26B_q4_0-it.gguf',
    size_bytes: 14439361440,
    quant: 'Q4_0',
    blurb: 'A large mixture-of-experts Gemma — strongest reasoning and quality.',
  },
]
